version: "3.7"
services:
  server:
    image: node:12.14-stretch-slim
    ports:
      - "56000:8080"
    volumes:
      - appData:/app:cached
    working_dir: /app
    environment:
      - DEBUG=*
      - PORT=8080
      - DB_URL=postgresql://superuser:superuserpass@database:5432/db-sample
    command: 'bash -c "/app/scripts/wait-for-it.sh database:5432 --timeout=60 -- npm run start:dev"'
    restart: always
    depends_on:
      - database
  database:
    image: postgres:12-alpine
    ports:
      - "57000:5432"
    volumes:
      - appData:/app:cached
      - ./.docker/postgresql.conf:/etc/postgresql/postgresql.conf
    #working_dir: /app/packages/backend
    environment:
      - POSTGRES_INITDB_ARGS="--no-locale"
      - POSTGRES_USER=superuser
      - POSTGRES_PASSWORD=superuserpass
      - POSTGRES_DB=db-sample
    command: 'postgres -c "config_file=/etc/postgresql/postgresql.conf"'
    restart: always

volumes:
  appData:
    driver_opts:
      type: none
      device: ${PWD}
      o: bind
